from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, Sequence, Any


@dataclass(frozen=True, slots=True)
class StatusHandle:
    chat_id: int
    message_id: int


class StatusAnimatorPort(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...

    async def begin(self, *, chat_id: int, text: str) -> StatusHandle: ...
    def attach(self, *, chat_id: int, message_id: int) -> StatusHandle: ...

    async def set_text(self, handle: StatusHandle, text: str, *, reply_markup: Any | None = None) -> None: ...
    async def start_loop(self, handle: StatusHandle, *, frames: Sequence[str]) -> None: ...
    async def stop_loop(self, handle: StatusHandle) -> None: ...
    async def finish(self, handle: StatusHandle, *, text: str) -> None: ...
    async def fail(self, handle: StatusHandle, *, text: str) -> None: ...
